name: Run Tests and Generate Coverage Report

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ] 

jobs:
  test-and-report:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Run tests with coverage
      run: dotnet test DotTestKit.UnitTests/DotTestKit.UnitTests.csproj --collect:"XPlat Code Coverage"

    - name: Install ReportGenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool

    - name: Add ReportGenerator to PATH
      run: echo "$HOME/.dotnet/tools" | Out-File -Append -Encoding ascii $env:GITHUB_PATH

    - name: Generate HTML report
      run: |
        $coverageFile = Get-ChildItem -Recurse -Filter "coverage.cobertura.xml" | Select-Object -First 1
        reportgenerator -reports:"$coverageFile" -targetdir:"DotNetCoverageReport" -reporttypes:Html

    - name: Upload HTML Report
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-code-coverage-report
        path: DotNetCoverageReport

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Angular dependencies
      working-directory: OMSClient
      run: npm ci

    - name: Run Angular tests with coverage
      working-directory: OMSClient
      env:
        NODE_OPTIONS: --openssl-legacy-provider
      run: |
        npx ng test --code-coverage
        echo "Angular tests completed."

    - name: Upload Angular Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: angular-code-coverage-report
        path: OMSClient/src/coverage/omsclient
